package com.arch.design_system.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFF4F4FA)
val md_theme_dark_onPrimary = Color(0xFF16161A)
val md_theme_dark_primaryContainer = Color(0xFF930005)
val md_theme_dark_onPrimaryContainer = Color(0xFFFCFCFC)
val md_theme_dark_secondary = Color(0xFFC2221C)
val md_theme_dark_onSecondary = Color(0xFF690002)
val md_theme_dark_secondaryContainer = Color(0xFF930005)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_tertiary = Color(0xFFFFB4A9)
val md_theme_dark_onTertiary = Color(0xFF690002)
val md_theme_dark_tertiaryContainer = Color(0xFF930005)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24242A)
val md_theme_dark_onBackground = Color(0xFFFCFCFC)
val md_theme_dark_surface = Color(0xFF2D2D35)
val md_theme_dark_onSurface = Color(0xFFFCFCFC)
val md_theme_dark_surfaceVariant = Color(0xFF34343D)
val md_theme_dark_onSurfaceVariant = Color(0xFFFCFCFC)
val md_theme_dark_outline = Color(0xFFA08C89)
val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
val md_theme_dark_inversePrimary = Color(0xFFB91C17)
val md_theme_dark_surfaceTint = Color(0xFFFFB4A9)
val md_theme_dark_outlineVariant = Color(0xCCFCFCFC)
val md_theme_dark_scrim = Color(0xFF000000)